---
title: "Article analysis n° 3"
author:
  - name: Aimeric Vandescure
    url: {}
date: 11-13-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

**Candida auris** : The new superbug on the block


## II Name of the Magazine + Source [URL]:

BBC https://www.bbc.com/news/health-49170866


## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To fear             |         To be scared                   |
|   An outbreak       | A spread of an infectious disease        |
| To rise             | To increase         |
| To be unwell        | To be sick |
| A thrush            | Oropharyngeal candidasis, a proliferation of **Candida albicans** in the mouth and throat |

## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Lena Ciric, gratuated in the biological sciences at the university of Oxford. |
| Published in?                | 17 August 2019                                                       |
| General topic?               |A recently found incfetious yeast related to **Candida albicans** floods the hospitals from developed countries around the world.                     |
| Procedure/what was examined? | Resaerchers found that  |
| Conclusions/discovery?       |  Doctors needs to be informed how to recognize this yeast to better treat it and how to prevent outbreaks in hospitals.      |
| Remaining questions?         | How did the resistance genes pass from one speciesto the another ? |

