---
title: "Article analysis n° 2"
author:
  - name: Aimeric Vandescure
    url: {}
date: 10-30-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Improved Biobutanol Production in 2-L Simultaneous Saccharification and Fermentation with Delayed Yeast Extract Feeding and in-situ Recovery


## II Name of the Magazine + Source [URL]:

Nature https://www.nature.com/articles/s41598-019-43718-1?fbclid=IwAR0ONlBsLQY7Vrpa8RJsE4mE1NX82fFP9T8VD9WnEB9wbCj5PDtthqjePsg


## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To make appealing   | To make you want                   |
| To delay            | To retard         |
| To enhance          | To improve     |
| To trigger          | Help to cause     |
| A threshold         | A start point   |
| To pull upward       | Help to reach a goal   |
| A recovery          | A rehabilitation   |
| Prior to            | Before           |
| Soaked             | Put in a liquid |
| Sealed             | Hermetic       |
| A stripping        | An extraction     |

## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Muhammad Siddiq Mohamed Salleh, Mohamad Faizal Ibrahim, Ahmad Muhaimin Roslan & Suraini Abd-Aziz |
| Published in?                | 15 May 2019                                                       |
| General topic?               | The biobutanol produced from oil palm empty fruit brunch (OPEFB) by fermentation is an altrnative to butanol produced by a petrochimical process.|
| Procedure/what was examined? | The OPEFB is first processed to be fermented, an inoculum preparation must be prepared with a *Clostidium acetobutylicum* strain in cultured medium. Then you could make separate hydrolysis and fermentation but a simultaneous saccharification and fermenentation is more efficient. So the method includes to put 1,5L of acetate buffer in a 2L bioreactor with 5% of pretreated OPEFB, 15% of the prepared inoculum and 6g/l of yeast extact, the mixture have to be sparged with nitrogen to get the oxygen out. You can also improve the process by delaying yeast exctact feeding, indeed if you put the yeast exctrat after 39h, the acid production will decrease and the yield will be enhaneced but you can still improve it by in situ recovery using gas stripping. Here, nitrogen is circulated at 1,5l/min through the mixture after the biobutanol concentration reched 1g/l (after 48h of fermentation), it goes until the end of the fermentation and a condenser allows the collection of a fairly pur biobutanol (83%).|
| Conclusions/discovery?       | Simultaneous saccharification and fermentation with delayed yeast extract feeding and in situ recovery has a better yield (16%) and a better biobutanol production (4,96 g/l) than other processes.    |
| Remaining questions?         | Maybe could we use another substrate who has better yield than OPEFB ? |




