---
title: "Article analysis n° 6"
author:
  - name: Aimeric Vandescure
    url: {}
date: 02-10-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Scientists uncover new mode of evolution


## II Name of the Magazine + Source [URL]:

LiveScience  qu'elles n'en gagnent de nouveaux

## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To stick   | To persist, to last                   |
|   To alter     | To change         |
|  To dig   |  To search  |
|  To unfurl  |   To unroll   |
| To swoop  | To hurry up  |
|  A track  |  A trace  |
|  A petri dish  |  A box to develop microorganisms  |
|  To retain  |  To keep  |
|  To outcompete  |  To exceed  |
|  A leap  |  A jump, hop  |
|  At whim  |  As much as you want, as desired  |

## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Nicoletta Lanese and Staff Writter                        |
| Published in?                | January, 21 2020                                                       |
| General topic?               |  The discovery of a yeast, *Cryptococcus neoformans* makes it possible that methyl groups around DNA are de support of Evolution and Natural selection.                     |
| Procedure/what was examined? | That's groups allow to turn genes on or off and that are not expected to be present in yeats and invertebrates. An organism wich have methyl groups contains some "Novo methyltransferase" wich sticks methyls on DNA and some "maintenance methyltransferase" which copies methyls on the new half of DNA during cell division. *C.neoformans* only has maintenance enzyme so it can't copy methyls indefinitely beacuse there are mistakes with each cell division, in addition scientists discovered that random methyls groups can appear but the yeasts lost methyls twenty times faster. |
| Conclusions/discovery?       |  In conclusion if yeast has not disappeared yet, it's because there are advantages, methyls increases survivability, protects the genome from attacks and prevents jumping genes, called transposons, to jump into a survival gene. So individuals with a high density of methyls are more able to survive.      |
| Remaining questions?         | Does this form of evolution exist in other organisms ? Or other forms of evolution in other yeasts ? |

