---
title: "Article analysis n° 5"
author:
  - name: Aimeric Vandescure
    url: {}
date: 11-19-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Yeasts in nectar can stimulate the growth of bee colonies


## II Name of the Magazine + Source [URL]:

Science Daily  https://www.sciencedaily.com/releases/2019/11/191120131323.htm

## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To comput   | To count                  |
|  A foraging behaviour    | An eating behaviour         |
|    Fewer   |  Less than   |
|A disruption    | A perturbation  |
| A threat     | A dangerous thing    |

## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | /                        |
| Published in?                | November, 20 2019                                                       |
| General topic?               |  Biologists from KU Leuven Biology Department set out to demonstrate that nectar modified by yeasts can influence the health of a bumblebee *Bombus terrestris* colony.                       |
| Procedure/what was examined? | This is achieved by observing the behaviour of bees into an artificial flower field containing one half with flowers wich contain a nectar-like solution and another half wich contain the same solution with different strains of yeast. Then they looked at which part of the field was the most visited by bees and how much time. Finally they studied differences in the weel-beeing of the bumblebees.|
| Conclusions/discovery?       |  (what did the researchers conclude? Did they find something?)      |
| Remaining questions?         | How does yeast influence the live of pollinators ? Are they main actors in the live of pollinators?|

Questions :

https://phys.org/news/2019-08-probiotic-yeast.html

https://www.sciencedaily.com/releases/2019/12/191203143314.htm 


