---
title: "Article analysis n° 4"
author:
  - name: Aimeric Vandescure
    url: {}
date: 12-02-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Exploiting parasitic yeast to kill yeast pathogens


## II Name of the Magazine + Source [URL]:

Science Daily  https://www.sciencedaily.com/releases/2019/05/190509142839.htm


## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| Healthcare burden   | Treatments accessible           |
|  A draft       | A project         |
| To trigger   | To cause    |
| To break down     | To destroy    |
| A prey    | What a predator eats    |
| An insight    | An information    |
| An avenue     |  A way, a manner   |
| To monitor      | To watch by a computer     |

## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Klara Junker, Anna Chailyan, Ana Hesselbart, Jochen Forster, Jürgen Wendland.                        |
| Published in?                | May 9, 2019                                                       |
| General topic?               |  Researchers discovered a type of yeast *Sacchahromycopsis schoenii* which is able to destroy another type of multi-resistant yeast *Candida auris* by predation.    |
| Procedure/what was examined? | They sequenced, assembled and annoted a draft genome of S.schoenii to understand the predacious behaviour of the yeast and they observed living cells under a microscope to monitor this behaviour under different appoaches.  |
| Conclusions/discovery?       |  By a lack of nutrients, the yeast becomes predator, the researchers also found that *S. schoenii* produce aspartic proteases to destroy the membrane of the prey. Thererfore this antifungal proprety could be used to produce a biocontrol agent.|
| Remaining questions?         | What are they doing with the remaining yeasts *S. schoenii* ? |

For more information about the spread of the multi-drug resistant yeast *Candida auris* click [here](https://www.bbc.com/news/health-49170866)




