---
title: "Article analysis n° 1"
author:
  - name: Aimeric Vandescure
    url: {}
date: 10-18-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Production of Fungal Phytases from Agroindustrial Byproducts for Pig Diets 


## II Name of the Magazine + Source [URL]:

Nature https://www.nature.com/articles/s41598-019-45720-z


## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| Corn meal           | Powder of corn                 |
| Rice bran           | Seed waste of rice             |
| Thus                | So                             |
| Knowledge           | Thing you know                 |
| Production media    | Production support             |
| An assay            | A dosage                       |
| Quenched            | Put in a liquid                |
| The yield           | The efficiency                 |
| Raw materials       | Initial products               |


## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Elizabeth Bárbara Epalanga Pires, Anderson Junior de Freitas, Fernanda França e Souza, Rafael Locatelli Salgado, Valéria Monteze Guimarães, Francisco Alves Pereira & Monique Renon Eller from Universidade Federal de Viçosa.                         |
| Published in?                | 25 June 2019                                                       |
| General topic?               | The article talks about a way to find the best fungi to produce low-cost phytatses which are enzymes to metabolize phosphorus. Indeed pigs are not able to synthesize phytase so we give him some extra phosphorus in its diet which is expensive and bad for the environment. |
| Procedure/what was examined? | So to find the best fungi you have to select the fungus strain, the substrate, the culture conditions i.e the time incubation, the temperature, the pH, the substrate concentration.Then, the phytase activity have to be measured according to the effect of pH, temperature, the thermostability of the phytases and the effect of the metal ions. Finally, statistical analysis must be made. |
| Conclusions/discovery?       | Use the yeast *Kluyveromyces marxianus* is a great alternative to reduce the cost of phytase production due to its stability to different factors, a shorter generation time and its high productivity. Another candidate is *Acremonim zeae* but not as efficient as yeast.     |
| Remaining questions?         | All questions have been addressed. |


