---
title: "Article analysis n° 4"
author:
  - name: Aimeric Vandescure
    url: {}
date: 12-01-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I Title of the article: 

Yeasts in nectar can stimulate the growth of bee colonies


## II Name of the Magazine + Source [URL]:

Science Daily  https://www.sciencedaily.com/releases/2019/11/191120131323.htm

## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To comput   | To count                  |
|  A foraging behaviour    | An eating behaviour         |
|    Fewer   |  Less than   |
|A disruption    | A perturbation  |
| A threat     | A dangerous thing    |

## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | María I. Pozo, Gaby Kemenade, Annette Oystaeyen, Tomás Aledón‐Catalá, Alfredo Benavente, Wim Van den Ende, Felix Wäckers, Hans Jacquemyn from the KU Leuven Biology Department.                         |
| Published in?                | November 20, 2019                                                       |
| General topic?               |  Biologists from KU Leuven Biology Department set out to demonstrate that nectar modified by yeasts can influence the health of a bumblebee *Bombus terrestris* colony.                       |
| Procedure/what was examined? | This is achieved by observing the behaviour of bees into an artificial flower field containing one half with flowers wich contain a nectar-like solution and another half wich contain the same solution with different strains of yeast. Then they looked at which part of the field was the most visited by bees and how much time. Finally they studied differences in the weel-beeing of the bumblebees.|
| Conclusions/discovery?       |Actually the result is that there are no differences in visit frequencies between the two parts nor time on flower differences. However they noticed that bees can absorb yeast cells although the nutrients concentration is quite high in addition in certain strains of yeast generate more larvae wich become worker bee.|
| Remaining questions?         | How does yeast influence the live of pollinators ? Are they main actors in the live of pollinators?|



