---
title: "Article analysis n° 8"
author:
  - name: Aimeric Vandescure
    url: {}
date: 03-15-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## I Title of the article: 


A simplified way to turn food waste into hydrogen energy


## II Name of the Magazine + Source [URL]:

Perdue University  https://www.purdue.edu/newsroom/releases/2020/Q1/a-simplified-way-to-turn-food-waste-into-hydrogen-energy.html

## III Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| To discard   | To throw                    |
|  To cut down   | To reduce         |
|  To break down  | To degrade  |
|  To grind  |  To crush   |
|  Stand-alone   |  Autonomous  |
|  To patent  |  To protect an idea |


## IV Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |  R.Kramer, a professor at Energy and the Environment and Purdue University Northwest.                        |
| Published in?                | January 7, 2020                                                       |
| General topic?               |A university professor manages to improve the transformation food waste into hydrogen by using yeasts in a reactor.                   |
| Procedure/what was examined? |The current method transformation uses bacteria to produce hydrogen, this method is slow and needs a complicated pre-processing steps. The new method uses yeast instead of bacteria, such substitution allows a faster process, less pre-processing steps and a production of hydrogen increased by 20-25%, it also reduces the probability of explosion due to hydrogen. Food waste is a big problem in developed countries, indeed $200 billion a year is wasted in America so this innovation seems to be a solution.                 |
| Conclusions/discovery?       | Several innovations related to the replacement of bacteria by yeasts in the basic method result in small improvements but this one focuses on family seeking autonomy because it can work with solar thermal technology and needs only wastes, yeast and the machine.                    |
| Remaining questions?         |  Is it possible to adapt the installation to a smaller version?                    |




