---
title: "My english activity log  M.E.A.L"
date: 10-09-2019
output:
  distill::distill_article:
    self_contained: false
---

10/09/19 Today I used RStudio to see how the blog work
I also found a lot of articles in the site "nature.com" about yeasts, very interesting

10/20/19 I'm already looking for another article about yeasts in biotechnologies and especially in the food industry.

10/21/19 A new article appeared today, about yeast in the world of the beer this time.
I wasn't planning to talk about this subject but the hybridization of the yeast really interets me.

10/27/19 I have watched CNN News for 3 monts, i do not watch tv often but when i'm watching for tv, it's CNN yo follow the actuality.

10/30/19 Well, the article about beer and hybridation is now payable so i will not talk about beer for now.
But i'll probably talk about hybridization soon.

11/16/19 I regulary watch for culinary recipes and on youtube.
These days, i'm trying to find recipes that I can make easiy in weeks to avoid the routine.

01/03/20 This morning I watched the news on CNN and it was not usual, that talked about the murder of an iranian general under the order of Trump and a possible future war.
I was worried at first but I think it will pass.

10/02/20 For this quarter, I will try to use the data science course in English articles.

Klara Junker, Anna Chailyan, Ana Hesselbart, Jochen Forster, Jürgen Wendland.
